generator:
  class: sfDoctrineGenerator
  param:
    model_class:           dakLocationReservation
    theme:                 dakAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          dak_location_reservation_admin
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        statusString: { label: "Status" }

        activateEmbedRequirementLightSound: { label: Make use of light and sound? }
        embedRequirementLightSound: { label: " " }

        activateEmbedRequirementPhotography: { label: Would you like photography? }
        embedRequirementPhotography: { label: " " }

        activateEmbedRequirementCatering: { label: Do you need catering? }
        embedRequirementCatering: { label: " " }
      list:
        sort: [created_at, desc]
        max_per_page: 10
        display: [=title, statusString, arranger, location, activatedRequirements, created_at, updated_at]
        table_method: defaultJoins
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
