generator:
  class: sfDoctrineGenerator
  param:
    model_class:           dakArranger
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          dak_arranger_admin
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _new:
          credentials: [admin]
        _delete:
          credentials: [admin]
      fields:  ~
      list:
        max_per_page: 10
        sort: [name, asc]
        title: Arranger management
        display: [=name, created_at, updated_at]
      filter:  ~
      form:    ~
      edit:
        title: Editing arranger "%%name%%"
      new:
        title: Arranger creation
