# Security and access definitions for arranger module

new:
  credentials: [admin]

create:
  credentials: [admin]

delete:
  credentials: [admin]

batchDelete:
  credentials: [admin]

edit:
  credentials: [[admin, owner]]

update:
  credentials: [[admin, owner]]
