<?php

/**
 * locationAccessoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PlugindakLocationAccessoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object locationAccessoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('locationAccessory');
    }
}
