<?php

/**
 * PlugindakFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PlugindakFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object dakFile
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('dakFile');
    }
}
