<?php

/**
 * requirementLightSoundTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PlugindakRequirementLightSoundTable extends PlugindakLocationReservationRequirementBaseTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object requirementLightSoundTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('dakRequirementLightSound');
    }
}
