<?php

/**
 * arrangerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PlugindakArrangerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object arrangerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('dakArranger');
    }

    public function defaultJoins(Doctrine_Query $q)
    {
        return $q;
    }

    public function defaultSelect(Doctrine_Query $q) {
        //This function assumes you've used eventTable::defaultJoins
        return $q;
    }

    public function defaultOrderBy(Doctrine_Query $q)
    {
        $rootAlias = $q->getRootAlias();

        $q->orderBy($rootAlias . '.name asc');

        return $q;
    }

    public function defaultQueryOptions(Doctrine_Query $q)
    {
        $this->defaultJoins($q);
        $this->defaultSelect($q);
        $this->defaultOrderBy($q);
    }
}
