<?php

/**
 * locationReservationRequirementBase
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * This class has been set to abstract because this specific table
 * is not required and is not supposed to be created.
 *
 * @package    kvarteret_events
 * @subpackage model
 * @author     Endre Oma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PlugindakLocationReservationRequirementBase extends BasedakLocationReservationRequirementBase
{
}
