<?php

/**
 * requirementCatering
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kvarteret_events
 * @subpackage model
 * @author     Endre Oma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PlugindakPicture extends BasedakPicture
{

  /**
   * Will delete the picture when the corresponding
   * record is deleted
   */
  public function postDelete ($event)
  {
    @unlink(sfConfig::get('sf_upload_dir').'/dakpicture/'.$this->filename);
  }

  public function getFile()
  {
    return 'dakpicture/' . $this->getFilename();
  }
}
