<?php

/**
 * festivalArrangerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PlugindakFestivalArrangerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object festivalArrangerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('festivalArranger');
    }
}
