<?php

/**
 * locationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PlugindakLocationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object locationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('location');
    }
}
