<?php

/**
 * eventCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PlugindakEventPictureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object eventCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('dakEventPicture');
    }
}
