<?php

/**
 * event
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kvarteret_events
 * @subpackage model
 * @author     Endre Oma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PlugindakEvent extends BasedakEvent
{

  protected $purifier = null;

  protected $previousIsPublic = null;

  /**
   * Returns recurring location if location_id is set, 
   * if not it will return custom location
   */
  public function getLocation ()
  {
    if (!$this->location_id) {
      return $this->customLocation;
    } else {
      return $this->getCommonLocation()->getRenderedLocationHierarchy();
    }
  }

  /**
   * Will check if myHTMLPurifier has been initiated, if not, initiate it.
   */
  protected function myHTMLPurifierInstance() {
    if (empty($this->purifier)) $this->purifier = new myHTMLPurifier();
  }

  /**
   * setDescription will escape and remove illegal tags and script in description.
   * We'll only allow certain tags, and certain attributes on tags
   */
  public function setDescription ($value) {
    $this->myHTMLPurifierInstance();

    $this->_set('description', trim($this->purifier->commonHtml($value)));
  }

  public function setLeadParagraph ($value) {
    $this->myHTMLPurifierInstance();

    $this->_set('leadParagraph', trim($this->purifier->blockHtml($value)));
  }

  public function setIsPublic ($value) {
    $this->previousIsPublic = $this->getIsPublic();

	$this->_set('is_public', $value);
  }

  public function postSave($event) {
    parent::postSave($event);

	// Takes care of notifying eventlisteners that
	// some data hase changed
    $dispatcher = ProjectConfiguration::getActive()->getEventDispatcher();

    if ($this->getIsPublic()) {
	  // Notify event listeners of updated data
      $dispatcher->notify(new sfEvent(null, 'dak.event.saved', array('id' => $this->getId())));
    } elseif (($this->previousIsPublic === true) && !$this->getIsPublic()) {
	  // Notify event listeners of data that should be removed
      $dispatcher->notify(new sfEvent(null, 'dak.event.deleted', array('id' => $this->getId())));
    }
 }

  public function postDelete($event) {
    parent::postDelete($event);

    $dispatcher = ProjectConfiguration::getActive()->getEventDispatcher();

    $dispatcher->notify(new sfEvent(null, 'dak.event.deleted', array('id' => $this->getId())));

  }
}
