<?php

/**
 * location
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kvarteret_events
 * @subpackage model
 * @author     Endre Oma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PlugindakLocation extends BasedakLocation
{

  /**
   * Will return a string with complete location hierarchy as string
   */
  public function getRenderedLocationHierarchy()
  {
    $nameHierarchy = '';

    $elem = $this;
    $nameHierarchy = $elem->getName();

    while ($elem->getNode()->hasParent()) {
      $elem = $elem->getNode()->getParent();
      $nameHierarchy = $elem->getName() . ', ' . $nameHierarchy;
    }

    return $nameHierarchy;
  }

}
