<?php

/**
 * festivalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PlugindakFestivalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object festivalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('festival');
    }

    public function defaultJoins(Doctrine_Query $q)
    {
        $rootAlias = $q->getRootAlias();

        $q->leftJoin($rootAlias . '.commonLocation l')
          ->leftJoin($rootAlias . '.arrangers a');

        return $q;
    }

    public function defaultSelect(Doctrine_Query $q) {
        //This function assumes you've used eventTable::defaultJoins

        $q->select('f.*, l.name, a.name');

        return $q;
    }

    public function defaultOrderBy(Doctrine_Query $q)
    {
        $rootAlias = $q->getRootAlias();

        $q->orderBy($rootAlias . '.startDate asc, ' .
                    $rootAlias . '.startTime asc, ' .
                    $rootAlias . '.title asc');

        return $q;
    }

    public function defaultQueryOptions(Doctrine_Query $q)
    {
        $this->defaultJoins($q);
        $this->defaultSelect($q);
        $this->defaultOrderBy($q);
    }
}
