<?php

/**
 * requirementCatering
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kvarteret_events
 * @subpackage model
 * @author     Endre Oma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PlugindakPicture extends BasedakPicture
{

  public function generateFilenameFilename (sfValidatedFile $file) {
    $imgData = getimagesize($file->getTempName());
	$this->setHeight($imgData[1]);
    $this->setWidth($imgData[0]);
    return parent::generateFilenameFilename($file);
  }

  /**
   * Will delete the picture when the corresponding
   * record is deleted
   */
  public function postDelete ($event)
  {
    @unlink(sfConfig::get('sf_upload_dir').'/dakpicture/'.$this->filename);

    
    // Remove all generated thumbnails
    $dispatcher = ProjectConfiguration::getActive()->getEventDispatcher();
    $thumbEvent = new sfEvent($this, 'sf_image_transform.changed_source', array(
     'sf_route' => 'dak_thumb',
     'type'  => 'dakPicture',
     'id'    => $this->id,
    ));
    $dispatcher->notify($thumbEvent);
  }

  public function postUpdate ($event)
  {

    // Remove all generated thumbnails
    $dispatcher = ProjectConfiguration::getActive()->getEventDispatcher();
    $thumbEvent = new sfEvent($this, 'sf_image_transform.changed_source', array(
     'sf_route' => 'dak_thumb',
     'type'  => 'dakPicture',
     'id'    => $this->id,
    ));
    $dispatcher->notify($thumbEvent);

  }

  public function getFile()
  {
    return 'dakpicture/' . $this->getFilename();
  }
}
