generator:
  class: sfDoctrineGenerator
  param:
    model_class:           dakEvent
    theme:                 dakAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          dak_event_admin
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        is_public: { label: Public?, help: Whether the event is public to the world }
        is_accepted: { label: Accepted?, help: Whether the event has been accepted by location owner }
        leadParagraph: { label: Lead paragraph, help: "A short description of the event, maximum 800 signs, including html elements" }
        customLocation: { label: Custom location }
        location_id: { label: Common location, help: "Specify common location, takes preferance over custom location" }
        primaryPicture_id: { label: Primary picture, help: "Optional. You can specify a primary picture to be shown in the event header" }
        pictures_list: { label: Additional pictures, help: "Optional. Specify additional pictures to be shown next to the event description" }
        startDate: { label: Start date }
        startTime: { label: Start time }
        endDate: { label: End date }
        endTime: { label: End time }
        festival_id: { help: Is this event supposed to be part of a festival? }
        covercharge: { help: "Can be any text or number up to 64 characters, not required" }
      list:
        max_per_page: 10
        title: Eventlist
        sort: [startDate, asc, startTime, asc, title, asc]
        layout: stacked
        display: [=title, startDate, updated_at]
        params: |
          %%is_accepted%% %%_linkToShowEvent%%<br />At %%location%% %%_mergedStartDateTime%% by %%arranger%%. %%_is_public%%<br />
          %%_eventHasFestival%%
          <small>Updated at %%updated_at%%. Created at %%created_at%%.</small>
        table_method: defaultJoinsAndRequirements # defaultJoinsAndRequirements will make it impossible to get event lists vefore current date
      filter:  ~
      form:
        display:
          - title
          - leadParagraph
          - description
          - is_public
          - is_accepted
          - startDate
          - startTime
          - endDate
          - endTime
          - covercharge
          - customLocation
          - location_id
          - categories_list
          - festival_id
          - primaryPicture_id
          - pictures_list
      edit:
        title: Editing event "%%title%%"
      new:
        title: Create new event
