
copy:
  credentials: [[admin, owner]]

edit:
  credentials: [[admin, owner]]

update:
  credentials: [[admin, owner]]

delete:
  credentials: [[admin, owner]]

batchDelete:
  credentials: [[admin, owner]]

