all:
  .settings:
    formats:
      list:
        quality: 90
        mime_type: image/jpeg
        transformations:
          - { adapter: GD, transformation: resize, param: { width: 130, height: 130, proportional: true } }
      primaryPicture:
        quality: 90
        mime_type: image/jpeg
        transformations:
          - { adapter: GD, transformation: resize, param: { width: 350, height: 200, proportional: true } }
      thumbnail_scale:
        quality:                75
        mime_type:              image/jpg
        transformations:
          - { adapter: GD, transformation: thumbnail, param: { width: 80, height: 80, method: scale}}
      thumbnail_fit:
        quality:                75
        mime_type:              image/jpg
        transformations:
          - { adapter: GD, transformation: thumbnail, param: { width: 80, height: 80, method: fit}}
