generator:
  class: sfDoctrineGenerator
  param:
    model_class:           dakFestival
    theme:                 dakAdmin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          dak_festival_admin
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        leadParagraph: { label: Lead paragraph, help: "A short description of the event, maximum 800 signs, including html elements" }
        customLocation: { label: Custom location }
        location_id: { label: Common location, help: "Specify common location, takes preferance over custom location" }
        startDate: { label: Start date }
        startTime: { label: Start time }
        endDate: { label: End date }
        endTime: { label: End time }
        covercharge: { help: "Can be any text or number up to 64 characters, not required" }
      list:
        max_per_page: 10
        title: Festival list
        sort: [startDate, asc, title, asc]
        layout: stacked
        display: [=title, startDate, updated_at]
        params: |
          %%_linkToShowFestival%%<br />At %%location%% %%_mergedStartDateTime%% by %%_renderedFestivalArrangers%%.<br />
          <small>Updated at %%updated_at%%. Created at %%created_at%%.</small>
        table_method: defaultJoinsAndRequirements
      filter:  ~
      form:
        display:
          - title
          - leadParagraph
          - description
          - startDate
          - startTime
          - endDate
          - endTime
          - covercharge
          - customLocation
          - location_id
          - arrangers_list
      edit:    ~
      new:     ~
