generator:
  class: sfDoctrineGenerator
  param:
    model_class:           dakPicture
    theme:                 dakAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          dak_picture_admin
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        filename:
          label: Upload a file
          help: "Find a picture of type jpeg, png or gif to upload. Max <?php echo ini_get('upload_max_filesize') ?>B"
        tags:
          help: Set some tags making it easy to categorize and look up for later use.
      list:
        max_per_page: 40
        sort: [created_at, desc]
        title: Picture management
        display: [=description, _picture, created_at, updated_at]
      filter:  ~
      form:    ~
      edit:
        title: Editing picture
      new:
        title: Picture upload
